# Generated by Django 4.0.6 on 2022-08-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0002_rename_question_text_question_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionsl', models.CharField(max_length=1000)),
                ('vote', models.IntegerField(default=0)),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linksop', to='pollsapp.choice')),
            ],
        ),
    ]
